"""Initial migration.

Revision ID: 8d608ef733e4
Revises: 
Create Date: 2020-06-12 16:07:56.954584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d608ef733e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
                    sa.Column('id', postgresql.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('backend', sa.String(length=80), nullable=False),
                    sa.Column('path', sa.String(length=80), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('backend'),
                    sa.UniqueConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('path')
                    )
    # ### end Alembic commands ###

    op.execute('CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api')
    # ### end Alembic commands ###

    op.execute('DROP EXTENSION IF EXISTS timescaledb')
