name: Tests

on:
  - push

env:
  APP_ENV: test
  DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/portail?serverVersion=11&charset=utf8
  DASHBOARD_URL: http://localhost:3000
  DEPLOYMENT_USER: ubuntu
  DEPLOYMENT_HOST: localhost
  OAUTH2_ENCRYPTION_KEY: UBAlx0v3aJyGyQQOQF3XQ+ZeFFxlcKvWjWeKsHHyZN0=
  OAUTH2_PRIVATE_KEY_PATH: /home/runner/work/api-particulier-portail/api-particulier-portail/var/private.key
  OAUTH2_PUBLIC_KEY_PATH: /home/runner/work/api-particulier-portail/api-particulier-portail/var/public.key

jobs:
  api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: timescale/timescaledb:latest-pg11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: portail
        ports:
          - 5432:5432
      redis:
        image: redis:6
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer
      - name: Create empty .env file
        run: touch .env
      - name: Install dependencies
        run: composer install
      - name: Create openssl private key
        run: openssl genrsa -out var/private.key 2048
      - name: Create openssl public key
        run: openssl rsa -in var/private.key -pubout -out var/public.key
      - name: Run the tests
        run: ./bin/phpunit
      - name: Cat the logs when tests fail
        if: ${{ failure() }}
        run: cat var/log/test.log
